# "prod" suffix properties file. Scopes name samples: "prod", "web-prod", "api-prod", etc.
# Overrides application.yml default properties

spring:
  datasource:
    host: DB_MYSQL_DESAENV04_FRESCOSAPI_FRESCOSAPI_ENDPOINT
    db: frescosAPI
    username: frescosAPI_WPROD
    password: DB_MYSQL_DESAENV04_FRESCOSAPI_FRESCOSAPI_WPROD
    initialization-mode: always
  jpa:
    show-sql: false
    hibernate:
      ddl-auto: none
    database-platform: org.hibernate.dialect.MySQL8Dialect
